### ISSUE TITLE
Automated testing / any testing

### ISSUE THREAD

**Issue by RyanRio** [quasarbright/PongChamp#14]
Tracks all upcoming testing-related issues.

**Comment by quasarbright** [comment]
I've done something nice for integration tests before.

have a directory of files to run with code files and `.out` files for expected stdout and `.err` files for expected stderr:

https://github.com/quasarbright/HCC/tree/master/tests

Have a testing script that runs the program files capturing stdout/stderr and compares to corresponding expected output file contents:

https://github.com/quasarbright/HCC/blob/master/runtests.py

It's nice because we get integration tests that act like an implementation-agnostic specification for the semantics of the language
